### ISSUE TITLE
CraftTweaker and MineTweaker Collision

### ISSUE THREAD

**Issue by alexcombs1** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#1]
For version 3.3.1.1 on CurseForge, CraftTweaker and MineTweaker produce an error when loading the modpack. 

"You have mod sources that are duplicate within your system
Mod ID: File name
MineTweaker3: CraftTweaker-1.7.10-3.1.0-legacy.jar
MineTweaker3: MineTweaker3-1.7.10-3.0.10B.jar"

**Comment by yuesha-yc** [comment]
Note that, will be fixed.
