### ISSUE TITLE
流体固化器的问题

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#104]
**版本**
3.5.1.1

**描述**
流体固化器的问题。流体固化器表面的流体物体输入输出图案与实际不符。描述上顶部是输入口，左侧是物体输出，右侧是液体输出。而实际上机器的左侧显示的是物体输入，顶部则没有图案。

**Comment by yuesha-yc** [comment]
并非BUG，关闭
