### ISSUE TITLE
外星软锰矿生成伴生的钽铁矿在游戏中显示UNKNOWN矿石

### ISSUE THREAD

**Issue by yoyohunter13** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#106]
**版本**
3.5.1.1

**描述**
软锰矿伴生应有钽铁矿，但在HD星发现时以UNKNOWN矿石显示，挖下来后没有掉落物
![`S0R{J$6V}(D$IKF9BG@JM7](https://user-images.githubusercontent.com/74100905/105639025-e25e0680-5eb0-11eb-8ec5-fd94a17dfd79.png)

**Comment by yuesha-yc** [comment]
我回头确认一下

**Comment by yuesha-yc** [comment]
无法复现
