### ISSUE TITLE
任务书相关的建议

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#108]
**版本**
3.5.1.1
**描述**
蒸汽时代按照任务书的发展，蒸汽锅炉（钢）与蒸汽引擎（青铜）配合使用正好输出16KU，但是锅炉如果用的不是蒸馏水（钙化降低效率），会导致蒸汽引擎无法稳定输出16KU，会使前期的KU机器(破碎机)使用不了。所以建议：①在蒸汽引擎（青铜）增加必须使用蒸馏水描述。②让干燥器产蒸馏水作为蒸汽引擎（青铜）任务的前置任务。这样能更好的引导新手。

![image](https://user-images.githubusercontent.com/62133288/106451052-f6ad8f00-64c0-11eb-979e-36d9f9cab02a.png)
![image](https://user-images.githubusercontent.com/62133288/106451064-f9a87f80-64c0-11eb-86e7-7ccb00830a1a.png)
![image](https://user-images.githubusercontent.com/62133288/106451075-fe6d3380-64c0-11eb-838b-75f937002d05.png)

**Comment by yuesha-yc** [comment]
意义不大
