### ISSUE TITLE
燃烧室魔改建议

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#110]
**版本**
3.5.1.1
**描述**

- [x] 1.使用原版牛奶在GT凝结器做出的GT奶酪，在群峦传说中被视为水果而不是乳制品。

- [x] 2.现在群峦的钾盐只能使用石磨而不能使用碎石机，希望加一个合成表来照顾一下种田人。

- [x] 3.希望下版本把群峦传说中的所有金属粒的中文翻译一下，现在所有金属粒名称都是英文。

- [x] 4.[bug]在用原版桶装取胶乳后（树脂于榨汁机的产物），用小型漏斗给凝结器装胶乳，原版桶会消失。

- [x] 5.[优化]配方“100L胶乳+1硫磺粉→离心机→6橡胶混合液+40L胶水”，但在GT中，一单位物品熔融后为144L，而且1个树脂在榨汁机也是生成144L胶乳，所以这个100L非常容易在离心机中残留，显得不够科学（不够格雷？），所以麻烦改成108L胶乳或者144L胶乳。而且这个配方的橡胶产量真的大。

- [ ] 6.[优化]在进入蒸汽时代的时候，我发现很多产生HU或者使用HU的机器都有魔改，需要黑钢/红钢/蓝钢，但液体气体燃烧室并没有魔改，不知道是因为，会使用液体气体燃烧室的不是新人还是其他原因。因此提一个建议，在魔改这些产生HU/使用HU的机器配方的时候，只改变那个双层铜薄板，比如把双层铜薄板改成双层黑钢薄板什么的。而且由于GT的存在，也可以做三重四重五重甚至致密板，这样配方看起来美观一些。提出这个建议的原因是，看着燃烧室只改固体，还有看着GT熔炉的配方很难受。

在所有建议中，我最希望修改的是第5个建议，其他建议都不是特别重要，所以麻烦一定要实现第5个建议，拜托了！辛苦了！

**Comment by yuesha-yc** [comment]
1. 修复 2. 添加 3. 完成 4. 无法复现 5. 完成 6. 暂时需要考虑
