### ISSUE TITLE
对 结晶锗  的切割，NEI上面的“能量需求”和实际不符

### ISSUE THREAD

**Issue by ColdDown86** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#120]
**版本**
3.5.1.1

**描述**
对 结晶锗  的切割，NEI上面的“能量需求”和实际不符

**如何复现**
见下面“额外信息”
**期待情况**
修改

**额外信息**
![75_UBP4 I6KNX KBARTZP3](https://user-images.githubusercontent.com/73420461/107137324-75358100-6946-11eb-92e3-344de39910ed.png)
![C3%VB~CBF0E80A)S3%4G0@H](https://user-images.githubusercontent.com/73420461/107137330-81b9d980-6946-11eb-928d-b6f754cd93ea.png)

**Comment by yuesha-yc** [comment]
这是GT机器的超频机制导致的。对于32GU的配方，如果使用钢研磨机则需要四倍的功率进行超频。
