### ISSUE TITLE
 [Client thread/ERROR]: The mod DraconicEvolution (Draconic Evolution) requires mods [BrandonsCore] to be available

### ISSUE THREAD

**Issue by FidzgeraldGrout** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#122]
**Version**
Version of the modpack you are using [e.g. 3.6.0.0]

**Describe the bug**
After updating through CurseForge, the assembly caught an error with the absence of the BrandonsCore.

**To Reproduce**
1. Look at the assembly at CurseForge

[2021-02-12-1.log.gz](https://github.com/TerraFirmaRescue/TerraFirma-Rescue-Modpack/files/5967557/2021-02-12-1.log.gz)

**Additional context**
I downloaded it separately.

**Comment by yuesha-yc** [comment]
Fixed in 3.6.0.1
