### ISSUE TITLE
crusibles and drill dupe

### ISSUE THREAD

**Issue by boozzeeboom** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#13]
destroying crucibles with the drill dupes them

**Comment by yuesha-yc** [comment]
Which crucible? TFC or GT?
Which drill? GT electric ones?

**Comment by boozzeeboom** [comment]
when u destroy crucible WITH the drill (from quest-shop 30 coins) in the hand - crucible will duplicated

**Comment by yuesha-yc** [comment]
IDK what TFC does, its not very severe bug
