### ISSUE TITLE
净油器的声音实在是太太太吵了

### ISSUE THREAD

**Issue by Touture** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#131]
**你的建议和一个问题有关吗？如果是，请说明**
净油器这个东西实际使用起来过于痛苦，工作的声音让人的耳朵接受不了，千辛万苦做好了净油器启动后听到疯狂的爆炸声，还以为是机器负载过大，想用这个机器的话就必须把这东西放的远远的，没法放在家里
**描述的你的建议**
删除净油器的声音，让它和它的好兄弟蒸馏塔裂化塔一样安安静静的，或者改成更加柔和的声音

**Comment by yuesha-yc** [comment]
首先，请按照Issue格式写清楚版本号。

此问题已在3.6.0.1版本修复。
