### ISSUE TITLE
泰拉稿会被火红莲吃掉

### ISSUE THREAD

**Issue by Touture** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#135]
**Version of modpack｜整合包版本**

- 3.6.0.1

**Describe the bug｜描述问题**

- 泰拉稿被火红莲判定为燃料，在给泰拉稿升级的时候会被一边的火红莲吃掉

**How to reproduce｜如何复现**

- 泰拉稿丢在火红莲附近

**Expected behavior｜期待的修复情况**

- 让泰拉稿和博人传一样变成不可燃物

**Comment by yuesha-yc** [comment]
Who will throw a Terra Pickaxe beside the furnace flower....
谁会把泰拉镐子扔到火红莲旁边呢。。
