### ISSUE TITLE
离心机加工问题

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#139]
**Version of modpack｜整合包版本**

3.6.0.1

**Describe the bug｜描述问题**

离心机加工小撮的纯净镁矿石加工完了物品还在，会随机剩下几个镁，然后机器就处于待机状态，其他的矿石进不去，他也不接着加工镁

**Comment by yuesha-yc** [comment]
检查一下机器功率是否足够，区块是否加载。这应该是个罕见的问题。
