### ISSUE TITLE
民科蒸汽引擎问题

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#140]
**Version of modpack｜整合包版本**

3.6.0.1

**Describe the bug｜描述问题**

民科蒸汽引擎坩埚熔炼或研磨能出金和锡，但合成却不需要他们
![image](https://user-images.githubusercontent.com/62133288/109022212-947a2f80-76f6-11eb-87fd-95e7e8737da3.png)

**Comment by yuesha-yc** [comment]
所以魔改的合成也不便宜，整体来讲没人会这么干，GT回收配方无法删除，抱歉没法修复了
