### ISSUE TITLE
fluide dupe

### ISSUE THREAD

**Issue by boozzeeboom** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#16]
GT-wooden barrel when rightclick on TFC barrel (any wood) just add fluid to TFC and not taken from GT barrel

**Comment by yuesha-yc** [comment]
TFC barrel is literally Fucked Up. May you just wait when I got more time? I will fix them next time.

**Comment by yuesha-yc** [comment]
Fixed

**Comment by yuesha-yc** [comment]
Fixed
