### ISSUE TITLE
建议删掉部分大型机器“可超频”说明

### ISSUE THREAD

**Issue by NotRealLZX** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#166]
**Version of modpack｜整合包版本**

- 3.6.0.1

**Describe your suggestion｜描述你的建议**

- 游戏里面很多大型机器，都提示“消耗额外能量可以超频”，但实际情况并非这样。例如冷镏塔，我给4096CU/t，工作效率与1024CU/t几无区别。此外如果对研磨机提供大于4096RU/t的功率（总功率），即停止工作，并发出咔咔响声，可见根本没有超频的可能。因此建议要么给这些大型机器提供超频选项，要么就把主方块描述文本的“消耗额外能量可以超频”字段删掉，以免造成玩家误解。

**Comment by yuesha-yc** [comment]
请注意冷馏塔和大型研磨机都有最高的功率输入上限，高于此上限理所当然无法继续超频或者出现机械故障。
