### ISSUE TITLE
原版钓鱼竿获取添加

### ISSUE THREAD

**Issue by up2687894198** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#176]
**Version of modpack｜整合包版本**

- 3.6.0.1

**Describe your suggestion｜描述你的建议**

- 在这个整合包中，原版的钓鱼竿无法制作，因此玩家玩累了，想用原版鱼做GT食物或者钓钓鱼来养老就基本上不可能了。所以希望增加原版钓竿的合成表，推荐加到织布机里面。

**Comment by yuesha-yc** [comment]
如果你想的话你可以发个PR啦

**Comment by up2687894198** [comment]
发完了，我要种田。
