### ISSUE TITLE
多方块电池MFSU刷电BUG

### ISSUE THREAD

**Issue by Aeroblaze0314** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#184]
**Version of modpack｜整合包版本**

- 3.6.0.1

**Describe the bug｜描述问题**
多方块电池配合IV-LuV变压器、IVCO2激光器以及IV激光接收器刷电
- 

**How to reproduce｜如何复现**
多方块电池类型随意，螺丝刀调整输出电流32A；
通过任意符合电压电流的电线连接一台IV-LuV变压器；
一台变压器通过任意符合电压电流的电线连接4台IV激光器；
每2台IV激光器通过激光光纤连接1台IV激光接收器，激光接收器连接MESU背面输入电力；
一旦启动，在没有任何外部电源输入的情况下，MESU内部电量持续增加（ps：大概每台接收器8192EU/t）；
- 

**Expected behavior｜期待的修复情况**
尽早修复刷电bug。
-

**Comment by Aeroblaze0314** [comment]
Ps：新发现只要是5A及以上就行

**Comment by Aeroblaze0314** [comment]
Pss：最新发现与激光器无关，MESU设置电流越高，电池输出时电池本身电量损耗越小（比如我驱动一台激光器，我设置的输出电流越高，MESU本身消耗电量越少，消耗的电量与输出电量对不上。

**Comment by yuesha-yc** [comment]
3.6.1.0修复
