### ISSUE TITLE
Client timeout when connecting

### ISSUE THREAD

**Issue by lihe07** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#189]
**Version of modpack｜整合包版本**

- 3.5.1.2

**What's your operating system｜你的操作系统是什么**

- Server: Centos 7
- Client: Windows 11

**How to reproduce｜如何复现**

- Start a server, connect the server in the local network
- The latency is about 18ms
- 连接时，客户端无任何显示时（无响应中），服务器会在几十秒后踢出客户端，显示Timedout

**Comment by yuesha-yc** [comment]
更新至最新版本，无法复现。
