### ISSUE TITLE
Quest lines Steel or bronze.

### ISSUE THREAD

**Issue by boozzeeboom** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#19]
![2020-09-17_23-42-46](https://user-images.githubusercontent.com/21971234/93515024-615e9380-f941-11ea-8b1d-9482c91cf7cf.png)
After boiler quest told me - choose bronze or steel one will be enough. But it's wrong. You cant run steel crasher or compressor (for dense plate), cos basic steam engine can do 8-32 KU only, but steel mech needs 64-256. 
So you should made afte boiler bronze or steam engine, run bronze compressor, and THEN u can take line bronze or steel)
with this description about energy cost for steel mech, and steel mech quest line start not with basic steam engine only with Strong steel Engine who can made 32-128 KU

**Comment by yuesha-yc** [comment]
I would say GT6 has a very net-like tech tree. I can't make the quest too complicated or it will be very ugly and less apprehensible. I will add some texts to the compresser quest
