### ISSUE TITLE
Crash on open inv on server

### ISSUE THREAD

**Issue by datcat31** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#194]
**Version of modpack｜整合包版本**

- 3.6.0.1

**What's your operating system｜你的操作系统是什么**

- Win 10 Home

**How to reproduce｜如何复现**

- Login and open Inventory
[crash-2023-01-08_15.08.59-client.txt](https://github.com/TerraFirmaRescue/TerraFirma-Rescue-Modpack/files/10369395/crash-2023-01-08_15.08.59-client.txt)

**Comment by datcat31** [comment]
ive wiped the players playerdata but it was no help

**Comment by yuesha-yc** [comment]
Check MoeCraft mod. It is crashing the game. Not our issue.
