### ISSUE TITLE
进入游戏后手持物品时整个游戏变成一个颜色

### ISSUE THREAD

**Issue by Herminos** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#196]
**Version of modpack｜整合包版本**

- 3.6.0.1

**Describe the bug｜描述问题**

- 进入游戏后，手持物品时整个画面就会变成一个颜色，切换到空手时就正常
- 
![屏幕截图_20230127_110744](https://user-images.githubusercontent.com/114343654/215001716-f402137b-1eb8-4cb7-849a-5febf9cbbdb9.png)
这是正常的画面

![屏幕截图_20230127_110847](https://user-images.githubusercontent.com/114343654/215001783-3e285e9a-c62d-4b91-997a-3a42bc961009.png)

这是手持一个石子时的画面

**How to reproduce｜如何复现**

- 同上

**Expected behavior｜期待的修复情况**

- 希望手持物品时屏幕不会变成一个颜色

**Comment by Herminos** [comment]
使用JDK1.8.0里的JRE启动的·

**Comment by yys690** [comment]
我也遇到了这个问题，不过进入超平坦后的世界后恢复正常了

**Comment by Herminos** [comment]
目前更换了不使用Intel集显的电脑，不出现类似错误
应该是Inetl集成显卡驱动程序放弃了对1.7.10版本Minecraft所使用旧版本OpenGL API的支持，导致渲染出现bug
解决方法应该是使用优化mod[钕Neodymium](https://www.mcmod.cn/class/8761.html)
