### ISSUE TITLE
Can't install modpack via multimc

### ISSUE THREAD

**Issue by ni0ne** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#20]
Application hangs during installation

**Comment by yuesha-yc** [comment]
From which site did you download the pack from? Can you please give more detail?

**Comment by ni0ne** [comment]
Hi. I downloaded the package from
https://www.curseforge.com/minecraft/modpacks/terrafirma-rescue/files/3017082.
Then I imported the file into multimc and the program stuck at the import
stage of the mod list.
Then I installed the pack via twitch and copied the .minecraft folder in
multimc, which partially solved the problem...

чт, 24 сент. 2020 г., 00:59 YueSha <notifications@github.com>:

**Comment by yuesha-yc** [comment]
Partially solved? What do you mean?

**Comment by yuesha-yc** [comment]
Sorry we didn't support a MMC format package yet. You may need to install the entire modpack by twitch or technic to get all the mods. (I recommend Technic)

**Comment by ni0ne** [comment]
I wanted an easier way than this. But thanks anyway for your answer. I'll
try the Technic pack.

чт, 24 сент. 2020 г. в 01:18, YueSha <notifications@github.com>:
