### ISSUE TITLE
quest line change

### ISSUE THREAD

**Issue by boozzeeboom** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#24]
**tier 3 RF** - doesnt have any sence before you build the **Generifier** - cos some machines request the pure GT6 irons. So, make the stainless steel and generifier is one of the key - to open **tier 3 RF**.

**quest #89** for mangenese ore is - **main quest**, but i didnt found it and made the manganese from byproduct Silver (Bromargyrite ore) and take this stainless steel ingots. But still cant open **quest #32** cos this ore. So i think materials for **quest #89** should be replaced with manganese Ingot(dust plate etc.) and findind pure manganese ore should be not main quest some kind of sidequest who told you like: "if u find this ore, will be awesom and helpfull, but not nesessary as much". Same thing i think should be with **quest #86**

**Comment by yuesha-yc** [comment]
Thank you

**Comment by yuesha-yc** [comment]
Fixed
