### ISSUE TITLE
One more quest before #202

### ISSUE THREAD

**Issue by boozzeeboom** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#25]
i think should be one more quest before **quest #202**. **Quest for signalum alloy** - cos it's a little bit harder alloy then other, and if u make it like: putt all stuff to the crucible - u cant get this and will happened another alloy (sterling). So if there was some explanation like: "u should heated up redalloy+silver till 1500K and only then put some copper" - that will be rly helpfull.

**Comment by yuesha-yc** [comment]
Added
