### ISSUE TITLE
烤架造成区块内玩家无法进入服务器

### ISSUE THREAD

**Issue by nitu2003** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#28]
服务器是官方的 3.3.4.0 服务器然后手动更新到 3.4.4.0，除了更新方法里面需要的东西，其他全都没变。

#### 复现
就像教程一样把烤架放在锻造炉上面，然后放入任意的可以烧制的食物，然后就会被提出服务器（Disconnected from server）。
后台唯一一点有用的信息就是玩家第一次被提出服务器时的INFO
> [19:26:19] [Server thread/INFO]: Taskkill lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.util.ConcurrentModificationException

**Comment by yuesha-yc** [comment]
后面进行测试

**Comment by Evanenir** [comment]
简单修复的话可以直接删除发生问题的对应区块，我这里测试后暂时没有发现类似问题。
麻烦您尽量不要自行升级服务端整合包，出现任何bug官方均不保证修复。
