### ISSUE TITLE
Empty Food from Loot Bags

### ISSUE THREAD

**Issue by gamefreq0** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#29]
When opening a loot bag, if the reward is TFC food, it's created without any assigned weight, and seems to act as if it's 0 ounces.

**Comment by yuesha-yc** [comment]
It's a bug in BetterLootbags. I will remove all food rewards

**Comment by yuesha-yc** [comment]
Removed all TFC foods and added GT foods as rewards. Happy meal
