### ISSUE TITLE
no server files on curseforge

### ISSUE THREAD

**Issue by cadyb** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#3]
Curse forge doesn't have any server files for either of the 2 releases.

**Comment by yuesha-yc** [comment]
Eh server files will be uploaded later.

**Comment by cadyb** [comment]
We ended up making them on our own.
We had to disable ResourceLoader and update better questing to 3.0.328 as the version in the pack was crashing on world load.
Hopefully that takes some of the guess work out of it for you.
Thanks for the very nice pack we've been having a blast so far!

**Comment by yuesha-yc** [comment]
Make sure to use Thermos-Build53 as this is the only version that is stable ( I tested a long time ). ResourceLoader should definitely be deleted because it is a Client side mod.

**Comment by cadyb** [comment]
We aren't using bukkit at all as its a small private server for a couple of friends. The only stability issues we noticed is to occasional lag spike without the typical "server is behind by x ticks" message in the server console. Should we transition from just forge to thermos or are we fine if not using any sort of bukkit.

**Comment by yuesha-yc** [comment]
Basically it should be fine because forge server should be the most stable one. However I haven't noticed any of the lag spike using thermos. Maybe check your CPU and RAM?

**Comment by yuesha-yc** [comment]
Server file is uploaded. You can see it on Technic https://www.technicpack.net/modpack/terra-firma-rescue.1727928 
Click **server download**
