### ISSUE TITLE
群峦救援4430 合成类BUG

### ISSUE THREAD

**Issue by BarryChen614** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#38]
多方块储能单元MESU 配方四重橡胶锭缺少合成
双足飞龙套所需材料钻石套缺乏合成

**Comment by yuesha-yc** [comment]
第一个修复了。。

**Comment by BarryChen614** [comment]
堆叠的蓄水槽（有液体）右键tfc木桶可以填满木桶同时不会造成消耗,然后可以无限刷液体.

**Comment by yuesha-yc** [comment]
首先，不同的问题，请开一个新的Issue。你这个issue应该分解成3个。
第二，4430是什么？有这个版本吗。。。
最后，你「堆叠的蓄水槽（有液体）右键tfc木桶可以填满木桶同时不会造成消耗,然后可以无限刷液体.」这个问题是什么版本的？3.5.0.0 应该已经修复。

**Comment by BarryChen614** [comment]
3440我的锅
