### ISSUE TITLE
greg tech rods unable to be welded into long rods

### ISSUE THREAD

**Issue by cadyb** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#4]
I tested with both bronze and wrought iron gregtech rods.
Both rods had the welding temp tooltip.
I also tried a pair of cold rods as well.

![foofofof_035](https://user-images.githubusercontent.com/5795530/84097708-d3dfdf00-a9f4-11ea-8637-88d40294d9f0.png)
(plank was just to easily shift click in hot items quickly I also attempted to weld while it was removed)

steps to reproduce:
1. heat a pair of rods up to welding temp
2. put into the welding slots on an anvil with flux and hammer present
3. press weld

**Comment by yuesha-yc** [comment]
Which anvil were you using? GT parts processing require Steel Anvil or better, as can be seen in NEI.

**Comment by cadyb** [comment]
Yeah wasn't using a steel anvil my bad.
Closing.
