### ISSUE TITLE
Some mods in Chinese

### ISSUE THREAD

**Issue by sproott** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#42]
Animal crate and leather water sac mods are all in Chinese. Automated bellows have Chinese messages on them. Also, for me, GT Coke oven tooltip was in Chinese yesterday, but today it's English. So it seems to not load the translations properly sometimes.

**Comment by yuesha-yc** [comment]
The GT tooltip should be fixed as long as you don't use the GregTech.lang.
And those two mods seem to be created by Chinese authors and hardcoded those messages inside the mods... I need their source code to help.
