### ISSUE TITLE
Rolling machine recipes wrong

### ISSUE THREAD

**Issue by sproott** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#43]
The recipes in NEI are completely different from the ones you get when you click on recipes in the Rolling machine GUI.
NEI:
![image](https://user-images.githubusercontent.com/46423131/97278450-1b4af880-183a-11eb-9efb-c4ecf3ae928a.png)
Rolling machine:
![image](https://user-images.githubusercontent.com/46423131/97278596-403f6b80-183a-11eb-9ce1-a1b9864beda2.png)

**Comment by yuesha-yc** [comment]
A bug in NEI Integration I thought, which does not support RC x Minetweaker fully. Not really a big issue though.
