### ISSUE TITLE
GT items missing locale in TFC anvil

### ISSUE THREAD

**Issue by sproott** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#45]
If you put a steel sheet into a TFC anvil, the plan tooltips show "gui.plans.gtcasing" etc. instead of the localized name.

**Comment by yuesha-yc** [comment]
Is the only related to Steel Sheet or everything?

**Comment by sproott** [comment]
Only steel sheet afaik

**Comment by yuesha-yc** [comment]
I cannot reproduce the bug
