### ISSUE TITLE
Vanilla dirt in expert mode

### ISSUE THREAD

**Issue by sproott** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#46]
In FTB Expert mode, the vanilla dirt should not be possible to directly craft from TFC dirt. But it's possible to convert with Chisel. This should be disabled to preserve balance.

**Comment by yuesha-yc** [comment]
Chisel is really un-supported by ModTweaker and will remove all variations of the dirt from being chiseled, I guess it is just Okay to let it happen.
