### ISSUE TITLE
Wrong english text in new BlueLine menus

### ISSUE THREAD

**Issue by sproott** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#49]
For example, Singerplayer should be Singleplayer, quit the game should be with capital Q, Setting and Option should be Options, or Options and Settings, or something like that. 
I would make a pull request for this, but the text is in the rendered png files.

**Comment by GBLodb** [comment]
So so so sorry😂, our designer did a HUGE mistake.
Thank you for reporting!
