### ISSUE TITLE
群峦孔雀石缺乏对应的格雷矿处线路

### ISSUE THREAD

**Issue by yoyohunter13** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#61]
**Version**
Version of the modpack you are using [e.g. 3.5.0.0]

**Describe the bug**
群峦的孔雀石矿物可以通过RC碎矿碎成矿粒，但矿粒无法通过格雷破碎机或其他手段转换为粉碎矿物，NEI导向配方为黝铜

**To Reproduce**
直接对孔雀石矿粒进行NEI配方调查，或是将矿粒放入破碎机尝试检测

**Expected behavior**
希望修正该问题

**Comment by miaowwwwww** [comment]
实测破碎出来是一个黝铜，大概要改
