### ISSUE TITLE
龙研 双足飞龙剑没改伤害（其他龙研武器都改了

### ISSUE THREAD

**Issue by miaowwwwww** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#76]
**Version**
3.5.1.0

**Describe the bug**
龙研 双足飞龙剑没改伤害

**To Reproduce**
1. 打开moeg服务器
2. 查看双足飞龙剑伤害

**Expected behavior**
把它伤害改了，和别的龙研武器一样

**Comment by yuesha-yc** [comment]
Duplicate #52 ,closing
