### ISSUE TITLE
从某个角度向锭堆放置锭的时候，锭会放在旁边上但是手中不消耗，导致刷锭的出现

### ISSUE THREAD

**Issue by ColdDown86** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#80]
**版本**
3.5.1.1

**描述**
从某个角度向锭堆放置锭的时候，锭会放在旁边自己形成另一堆，但是手中锭没有减少

**如何复现**

如同描述，但是经过多次尝试只出现了两次，而且不知道该如何截图描述

**期待情况**
修复bug

**额外信息**
none

**Comment by ColdDown86** [comment]
破案了，是由于自动填充将我背包中的同种锭拿了出来，抱歉没有做过细致的测试就提交bug

**Comment by miaowwwwww** [comment]
可以自己关issue的

**Comment by Evanenir** [comment]
因为问题已经处理，issue协助关闭，谢谢您对我们整合包的支持。
TeamMoeg-Evan
