### ISSUE TITLE
不同材料在砧上用相同敲打方式产生不同效果

### ISSUE THREAD

**Issue by MrSeven590** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#81]
**版本**
3.5.1.1

**描述**
实测用锻铁板或者钢板在gt红钢砧上，用锤子敲打砧正面（有NEI字体的一面）即砧上弯曲敲打（大），会产生锻铁箔或钢箔
按照NEI合成表的查询，在“砧上弯曲敲打（大）”应该产生弯曲锻铁板或者弯曲钢板
在“砧上弯曲敲打（小）”应该产生弯曲锻铁箔或者弯曲钢箔＋4个废料
而青铜板则表现正常

实际与NEI合成表相反

**如何复现**
重复这个BUG的步骤
1. 放入锻铁板或者钢板
2. 锤子右键正面
3. 背包里产生锻铁箔或钢箔

**期待情况**
修正统一

**Comment by yuesha-yc** [comment]
经检测此bug无法复现
