### ISSUE TITLE
MV发电机问题

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#82]
**版本**
3.5.1.1

**描述**
在加入植魔后可通过地狱岩得到末地石，研磨成末地石粉，离心获得氦，从而直接做出电路组装机而跳了低温蒸馏塔的科技。。然后直接做出MV发电机。

**Comment by miaowwwwww** [comment]
btw, 离心萤石也是一样的能出氦哦

**Comment by yuesha-yc** [comment]
氦气本身就能从萤石获得，况且离心这些石头粉花费的能量也是很大的。

低温蒸馏塔的作用是获取那些真正的稀有气体：Ne, Xe, Kr 等
