### ISSUE TITLE
在泰拉星无法获取草来合成红石根

### ISSUE THREAD

**Issue by demisitike** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#85]
**版本**
3.5.0.0
**描述**
在泰拉星用剪刀剪草丛获得的只有高草，不能合成红石根

**如何复现**
使用四种剪刀破坏常规地形上生成的草获得的都是高草，不能用来合成红石根，使得植物魔法难以继续发展

**期待情况**
建议增加红石根的合成配方

**额外信息**
在低降雨地区获得的是矮草，也不能用

**Comment by miaowwwwww** [comment]
高草可以使用植魔的转换变成原版草，nei有的
