### ISSUE TITLE
魔力钻石问题

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#90]
**版本**
3.5.1.1

**描述**
新加入的植物魔法增加了获取魔力钻石的途径，同时在格雷的透镜中增加了魔力钻石透镜。

然而制作魔力钻石透镜所需要的魔力钻石物品ID与植物魔法中的id并不相同。

尽管在植物魔法的部分合成表中可以看到两种魔力钻石都可以用来合成，但能够制作透镜的钻石却只有一种。

**Comment by miaowwwwww** [comment]
魔力钻石透镜能做
