### ISSUE TITLE
熔融玫瑰金

### ISSUE THREAD

**Issue by Evanenir** [TerraFirmaRescue/TerraFirma-Rescue-Modpack#92]
**版本**
3.5.1.1
**描述**
熔融铜和熔融金无法合成熔融玫瑰金，缺少熔融玫瑰金合成
![image](https://user-images.githubusercontent.com/62133288/102630514-9cae6f80-4187-11eb-9d7e-2ba67c82ce40.png)

**Comment by yuesha-yc** [comment]
可以坩埚做
